### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by npgx** [MultiCubeUk/Modpack#3]
The server Kicked me off and then when i tryied to re-join the modpack crashed

**Comment by npgx** [comment]
UPDATE: when i break a sugar cane with an iron axe (or any thermal foundation axe) the servers kickes me and then when i try to rejoin the server, the modpack crashes

**Comment by SamKemp** [comment]
There is an issue with the modpack crashing if you try to join through the Hub. Don't do it, insted quit and use the join button on the home screen
