### ISSUE TITLE
Suggested "To add" mods

### ISSUE THREAD

**Issue by npgx** [MultiCubeUk/Modpack#5]
Inventory Tweaks
Mouse Tweaks
LiteLoader

**Comment by npgx** [comment]
Huge performance improvement server and client side: Stackie

**Comment by npgx** [comment]
Backpacks

**Comment by SamKemp** [comment]
Add suggestions to the bottom of the spreadsheet.
https://docs.google.com/spreadsheets/d/1QJLzYdtwh1shPms9a8-SXK31JTlBmBUrFbm_VmuuzbQ/edit#gid=0
