### ISSUE TITLE
Minor Bugs Section

### ISSUE THREAD

**Issue by npgx** [MultiCubeUk/Modpack#6]
Nobody can break blocks even with the correct tool, are we in adventure mode?

**Comment by npgx** [comment]
eating a steak replenish you all the hunger bar when holding shift it sayes it will give you 1 hunger point

**Comment by npgx** [comment]
Iron tools cannot mine anything, desc is:
"This tool cannot mine anything!
It can only be used for crafting"

**Comment by npgx** [comment]
somethimes iron swords one-hit kills mobs

**Comment by npgx** [comment]
all Thermal Foundation Picks can't mine any blocks, as also the spades and the axes or evensickle

**Comment by SamKemp** [comment]
Not really bugs. That is how Iguna Tinkers Tweaks works.

**Comment by bluejim31** [comment]
The tools in the starter kit are broken now - says flint pick, flint shovel and flint axe but they don't work. Item Id's are correct but the tools have no data.

**Comment by SamKemp** [comment]
Can you change the kit to the iron ones for me

**Comment by bluejim31** [comment]
however, it is fairly straight forward to get started with basic tools
and flint is craftable from 2 gravel :)

**Comment by bluejim31** [comment]
whats the command to set kits again?

**Comment by SamKemp** [comment]
http://dev.bukkit.org/bukkit-plugins/kitadder/

**Comment by bluejim31** [comment]
fixed. 1 iron sword and a golden shovel - added a chest instead of tools
:)
